management:
  endpoints:
    web:
      exposure:
        include: "*"
#spring:
#  cache:
#    infinispan:
#      config: infinispan.xml
#    jcache:
#      config: ehcache3.xml
#    caffeine:
#      spec: maximumSize=200,expireAfterAccess=600s